config/routes.rb
Rails.application.routes.draw do
  
  root 'posts#index'
  resources :posts do
  	member do
  		put "like", to: "posts#upvote"
  		put "dislike", to: "posts#downvote"
  		post "comments", to: "posts#comments"
  	end
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  has_attached_file :image, styles: { medium: "500x500>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  belongs_to :user
  acts_as_votable
  acts_as_commentable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  	@post = current_user.posts.build
  end

  def index
    @posts=Post.all.order('created_at desc')
  end

  def show
    @post=Post.find(params[:id])
    @comment=Comment.new
    @pullcomments=Comment.where(:commentable_id => params[:id])
  end

  def create
  	@post=current_user.posts.build(post_params)
  	if @post.save
  		flash[:sucess] ="success!"
  		puts 'success'
  		redirect_to post_path(@post)
  	else
  		flash[:error] =@post.errors.full_messages
  		puts 'error'
  		redirect_to new_post_path
  	end
  end

  def edit
    @post=Post.find(params[:id])
  end

  def update
    @post=Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, notice: "successfully updated"
    else
      render 'edit'
    end
  end

  def destroy
    post=Post.find(params[:id])
    comments=Comment.where(:commentable_id=>params[:id])
    post.destroy
    comments.destroy_all
    redirect_to action:'index', notice: "post deleted successfully"
  end

  def upvote
    @post=Post.find(params[:id])
    @post.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @post=Post.find(params[:id])
    @post.downvote_by current_user
    redirect_to :back
  end

  def comments
    commentable=Post.find(params[:id])
    comment=commentable.comments.new
    comment.user=current_user
    comment.title=params[:comment][:title].to_s
    comment.comment=params[:comment][:comment].to_s
    if comment.save
      redirect_to :back
    else
      redirect_to :back, notice: "please try again later"
    end

  end

  private
  	def post_params
  		params.require(:post).permit(:image,:Description)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Artrust</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   <style>
    body {
        padding-top: 70px;
        /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
    }
    </style>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "Artrust", root_url, class: "navbar-brand" %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <%- if current_user %>
	                    <li>
	                        <%= link_to "New Post", new_post_path %>
	                    </li>
                    	<li>
                    		<%= link_to "Logout",destroy_user_session_path, method: :delete,confirm: "wanna logout?"%>
                    	</li>
                    <% else %>
                    <li>
                    	<%= link_to "Login",new_user_session_path %>
                    </li>
                    <li>
                    	<%= link_to "Register",new_user_registration_path %>
                    </li>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <div class="container">

        <div class="row">
            <% flash.each do |a,b| %>
            <div class="alert alert-success"><%=b%> 
            </div>
            <%end%>
    			<%= yield %>
  		</div>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="col-md-6 col-md-offset-3">
<div class="row panel panel-default">
	<div class="panel-heading">
		<h1>Edit Post</h1>
	</div>
	<div class="panel-body">
		<%= form_for @post,html:{multipart: true} do |f| %>
			<table>
			<tr>
			<td>
				<%=f.label :image%>
			</td>
			<td>
				<%=f.file_field :image%>
			</td>
			</tr>
			<tr>
			<td>
				<%=f.label :Description%>
			</td>
			<td>
				<%=f.text_area :Description,style:'width:100%',required: true%>
			</td>
			<br>
			<tr>
			<td>
			<button class="btn btn-default btn-info" type="submit">Update Post</button>
			</td><td></td>
		<%end%>
	</div>
</div>
</div> 

app/views/posts/index.html.erb
<div id='posts' class="transitions-enabled">
	<%- @posts.each do |x| %>
		<div class="box panel panel-default">
		<%-if x.image.present?%>
			<%= link_to (image_tag x.image.url(:medium)), x %>
			<% end -%>
			<div class="panel-body">
			<%- if x.Description.to_s.length < 20 %>
				<h2><%= link_to x.Description, x %></h2>
				<%else%>
				<h4><%= link_to x.Description, x %></h4>
			<%end -%>
		<!-- 		<div class="btn-group pull-right">
					<%= link_to like_post_path(x),method: :put,class:"btn btn-default" do %>
						<span class="glyphicon glyphicon-heart">
							<%=x.get_upvotes.size%>
						</span>
					<%end%>
					<%= link_to dislike_post_path(x),method: :put,class:"btn btn-default" do %>
						<span class="glyphicon glyphicon-heart-empty">
							<%=x.get_downvotes.size%>
						</span>
					<%end%>
				</div> -->
				<br><br>
			</div>
		</div>
	<%end%>
</div>

app/views/posts/new.html.erb
<div class="col-md-6 col-md-offset-3">
<div class="row panel panel-default">
	<div class="panel-heading">
		<h1>New Post</h1>
	</div>
	<div class="panel-body">
		<%= form_for @post,html:{multipart: true} do |f| %>
			<table>
			<tr>
			<td>
				<%=f.label :image%>
			</td>
			<td>
				<%=f.file_field :image%>
			</td>
			</tr>
			<tr>
			<td>
				<%=f.label :Description%>
			</td>
			<td>
				<%=f.text_area :Description,style:'width:100%',required: true%>
			</td>
			<br>
			<tr>
			<td>
			<button class="btn btn-default btn-info" type="submit">create post</button>
			</td><td></td>
		<%end%>
	</div>
</div>
</div> 

app/views/posts/show.html.erb
<div class="col-sm-8 col-sm-offset-2">
<div class="panel panel-default">
	<div class="panel-heading">
	<%- if @post.Description.length < 50 %>
		<h1><%= @post.Description %></h1>
	<%else%>
		<h4><%= @post.Description %></h4>
	<% end -%>
	</div>
	<%- if @post.image.present?%>
	<div class="panel-body">
		<%= image_tag(@post.image.url(:medium)) %>
 	</div>
	<% end -%>
	<div class="panel-footer">
		<h4>Posted By:<%=@post.user.email%></h4>
			<div class="btn-group">
		<%-if current_user%>
			<%= link_to like_post_path(@post),method: :put,class:"btn btn-default" do %>
			<span class="glyphicon glyphicon-heart">
			<%=@post.get_upvotes.size%>
			</span>
			<%end%>
			<%= link_to dislike_post_path(@post),method: :put,class:"btn btn-default" do %>
			<span class="glyphicon glyphicon-heart-empty">
			<%=@post.get_downvotes.size%>
			</span>
			<%end%>
			<%if current_user.id==@post.user_id%>
				<%=link_to "Edit Post", edit_post_path, class:"btn btn-default btn-info"%>
				<%=link_to "Delete Post", post_path, class:"btn btn-default btn-danger",method: :delete,data:{confirm:"Are You sure?"}%>
			<%end%>
		<%else%>
			<%= link_to like_post_path(@post),method: :put,class:"btn btn-default", :disabled => true do %>
			<span class="glyphicon glyphicon-heart">
			<%=@post.get_upvotes.size%>
			</span>
			<%end%>
			<%= link_to dislike_post_path(@post),method: :put,class:"btn btn-default", :disabled => true do %>	
			<span class="glyphicon glyphicon-heart-empty">
			<%=@post.get_downvotes.size%>
			</span>
			<%end%>
		<%end%>
	</div>
</div>
<%-unless current_user.nil?%>
<div class="panel panel-default">
	<div class="panel-heading">
		<h1>add comment</h1>
	</div>
	<div class="panel-body">
		<%= form_for @comment, url: comments_post_path(@post) do |f| %>
			<table>
			<tr>
			<td>
				<%=f.label :title,"Expression" %>
			</td>
			<td>
				<%=f.text_field :title ,:class => "form-control",required: true%>
			</td>
			</tr>
			<tr>
			<td>
				<%=f.label :comment%>
			</td>
			<td>
				<%=f.text_area :comment,size: "50x2",:class => "form-control"%>
			</td>
			</tr><tr>
			<td>
			<button class="btn btn-default btn-info" type="submit">create post</button>
			</td><td></td></tr></table>
		<%end%>
	</div>
</div> 
<%-if @pullcomments.size==0%>
	<h4 class="panel panel-default panel-heading"> No Comments </h4>
<%else%>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h4 >Comments</h4>
		</div>
		<div class="panel-body">
			<ul class="list-group">
			<%-@pullcomments.each do |f| %>
  			<li class="list-group-item active"><%=f.title%></li>
  			<%-unless f.comment.nil?%>
  			<li class="list-group-item"><%=f.comment%></li>
  			<%end%>
  			<li class="list-group-item list-group-item-info">
			<%=f.user.email%> <span class="pull-right"><%= f.updated_at.localtime%></span>
  			</li>
  			<br>
			<%end%>
			</ul>

	</div>
</div>
<%end%>
<%end%>